name: 采集IP

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install requests

      - name: Run IP Collect
        run: python ip.py

      - name: Run Ping Cleanup
        run: python ping.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add max.txt
          git commit -m "自动更新：已完成节点采集与存活检测" || echo "no changes"
          git push origin main
