name: Auto IP Collect
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependence
        run: pip install requests

      - name: Run Script
        run: python ip_collect.py

      - name: Commit & Push
        run: |
          git config --global user.name "actions-bot"
          git config --global user.email "bot@github.com"
          git add max.txt
          git commit -m "auto update valid ip line" 2>/dev/null || true
          git push
